In [1]:
import numpy as np
np1=np.random.randn(2,3)#生成2行3列符合正态分布的二维数组
np1

array([[ 0.77268966,  0.86646615,  1.20829494],
       [-0.87427345, -3.23180153, -2.18198406]])

In [2]:
np.random.seed(3)#设置相同的seed,每次生成的随机数相同
np.random.rand(5)

array([ 0.5507979 ,  0.70814782,  0.29090474,  0.51082761,  0.89294695])

In [3]:
np.random.rand(5)

array([ 0.89629309,  0.12558531,  0.20724288,  0.0514672 ,  0.44080984])

In [4]:
np.random.seed(3)
np.random.rand(5)

array([ 0.5507979 ,  0.70814782,  0.29090474,  0.51082761,  0.89294695])

In [5]:
np.random.choice(5,3,replace=False)#生成1行3列没有重复的[0，5)的数

array([2, 3, 1])

In [6]:
np.random.choice(5,size=(3,2))

array([[1, 2],
       [0, 4],
       [4, 0]])